project:
  type: website
  output-dir: _site

website: 
  title: "IRC Latam"
  navbar: 
    left: 
      - text: "Home"
        href: index.qmd
  
execute:
  freeze: auto   # optional: only re-render if source changes

format:
  html: 
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    number-sections: false