project:
  type: website

website: 
  title: "IRC Latin America Client Numbers"
  navbar: 
    left: 
      - text: "Home"
        href: index.qmd
  output-dir: _site
  
format:
  html: 
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: false
    number-sections: false
    css: styles.css